project:
  type: website 
  output-dir: docs

website:
  title: "My Personal Website for STAT 37815" 
  navbar:
    tools:
      - icon: github
        href: https://github.com/kevguo2827/kevguo2827.github.io
    left:
      - href: index.qmd
        text: Home 
      - about.qmd
format:
  html:
    theme: zephyr
    mainfont: "'Open Sans', sans-serif"
    # css: my-style.css 
    # toc: true